# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 37df674b70bc7b7dbf67cc8fb56091f591ee2906269503d6592644d6fb23683e620f1dd0a5649c7f98befe928c256b92cd1b1948d37949d658e546b12bea9ae2

test:
  secret_key_base: f335e375642f889de2a05410a72817c86519ab176df15768d1a32670be7e4510d7f24e5addc7a97d0d1c5dbb6f27be66047b711c2ec9abeb53a0a2f87f87e081

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
